language: node_js

node_js:
  - '5'

notifications:
  email:
    on_success: always
    on_failure: always

sudo: false

cache:
  directories:
    - node_modules

install: 
  - npm install

script:
 # - npm run-script test-coverage
    - npm test

#after_success:  
#  - npm run-script coveralls

deploy:
  provider: cloudfoundry
  edge: true
  api: $CF_API
  username: $CF_USER
  password: $CF_PASS
  organization: $CF_ORG
  space: $CF_ENV
  skip_cleanup: true
